#!/usr/bin/env python3
"""
Generate skills/30-ai-security/<tool-name>/SKILL.md for every entry in
the awesome-ai-security curated list (MIT, by @ottosulin).

Credit: https://github.com/ottosulin/awesome-ai-security
"""

import os
import re
import textwrap

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT_DIR = os.path.join(ROOT, "skills", "30-ai-security")

# ─────────────────────────────────────────────────────────────────────────────
# Catalogue: (kebab_name, display_name, category, subcategory, description, ref_url)
# ─────────────────────────────────────────────────────────────────────────────
ENTRIES = [
    # ── Learning Resources ─────────────────────────────────────────────────
    ("owasp-ml-top-10", "OWASP ML TOP 10",
     "learning-resources", "reading-guides",
     "OWASP's top 10 security risks for machine learning systems.",
     "https://owasp.org/www-project-machine-learning-security-top-10/"),
    ("owasp-llm-top-10", "OWASP LLM TOP 10",
     "learning-resources", "reading-guides",
     "OWASP's top 10 security and safety risks for large language model applications.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),
    ("owasp-ai-security-guide", "OWASP AI Security and Privacy Guide",
     "learning-resources", "reading-guides",
     "Comprehensive guide covering AI security and privacy considerations.",
     "https://owasp.org/www-project-ai-security-and-privacy-guide/"),
    ("nist-airc", "NIST AIRC — Trustworthy & Responsible AI",
     "learning-resources", "reading-guides",
     "NIST Trustworthy and Responsible AI Resource Center.",
     "https://www.nist.gov/artificial-intelligence"),
    ("mlsecops-top-10", "The MLSecOps Top 10",
     "learning-resources", "reading-guides",
     "Top 10 MLSecOps risks by the Institute for Ethical AI & Machine Learning.",
     "https://ethical.institute/security.html"),
    ("owasp-multi-agentic-threat-modeling", "OWASP Multi-Agentic System Threat Modeling",
     "learning-resources", "reading-guides",
     "OWASP guide for threat modeling multi-agent AI systems.",
     "https://owasp.org/www-project-agentic-ai-threats-and-mitigations/"),
    ("owasp-mcp-cheatsheet", "OWASP MCP CheatSheet",
     "learning-resources", "reading-guides",
     "Practical guide for securely using third-party MCP servers.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),
    ("damn-vulnerable-mcp-server", "Damn Vulnerable MCP Server",
     "learning-resources", "courses-labs",
     "Deliberately vulnerable MCP implementation for educational purposes.",
     "https://github.com/harishsg993010/damn-vulnerable-mcp-server"),
    ("otto-support", "otto-support",
     "learning-resources", "courses-labs",
     "Vulnerable MCP server with tiered authentication (4 roles), 19 tools, sandboxed container. For practising privilege escalation and tool misuse.",
     "https://github.com/ottosulin/otto-support"),
    ("owasp-wrongsecrets-llm", "OWASP WrongSecrets LLM Exercise",
     "learning-resources", "courses-labs",
     "LLM-focused exercise in OWASP WrongSecrets.",
     "https://github.com/OWASP/wrongsecrets"),
    ("vulnerable-mcp-servers-lab", "Vulnerable MCP Servers Lab",
     "learning-resources", "courses-labs",
     "Collection of deliberately vulnerable servers for learning MCP pentesting.",
     "https://github.com/harishsg993010/vulnerable-mcp-servers"),
    ("finbot-ctf", "FinBot Agentic AI CTF",
     "learning-resources", "courses-labs",
     "CTF platform simulating real-world vulnerabilities in agentic AI using a Financial Services application.",
     "https://github.com/harishsg993010/FinBot-CTF"),
    ("ai-red-teaming-playground", "AI Red Teaming Playground Labs",
     "learning-resources", "courses-labs",
     "Infrastructure and labs for running AI red teaming trainings.",
     "https://github.com/Azure/AI-Red-Teaming-Playground-Labs"),
    ("damn-vulnerable-llm-agent", "Damn Vulnerable LLM Agent",
     "learning-resources", "courses-labs",
     "Intentionally vulnerable LLM agent covering prompt injection, tool misuse, and agent security.",
     "https://github.com/WithSecureLabs/damn-vulnerable-llm-agent"),
    ("ai-goat", "AI GOAT",
     "learning-resources", "courses-labs",
     "Damn Vulnerable LLM application with 10 challenges covering OWASP LLM Top 10. CTF-style lab.",
     "https://github.com/dhammon/ai-goat"),
    ("mlsecops-podcast", "MLSecOps Podcast",
     "learning-resources", "podcasts",
     "Podcast covering MLSecOps topics.",
     "https://mlsecops.com/podcast"),
    ("ai-security-podcast", "AI Security Podcast",
     "learning-resources", "podcasts",
     "Podcast focused on AI security topics.",
     "https://aisecuritypodcast.com/"),
    ("ai-security-ops-podcast", "AI Security Ops Podcast",
     "learning-resources", "podcasts",
     "Weekly podcast from Black Hills Information Security on AI security threats, tools, and trends.",
     "https://www.blackhillsinfosec.com/"),
    ("genai-security-podcast", "GenAI Security Podcast",
     "learning-resources", "podcasts",
     "Podcast dedicated to generative AI security.",
     "https://genaisecurity.com/"),

    # ── Governance & Risk Management ───────────────────────────────────────
    ("nist-ai-rmf", "NIST AI Risk Management Framework",
     "governance-risk", "frameworks",
     "NIST's framework for managing risk in AI systems throughout the lifecycle.",
     "https://www.nist.gov/system/files/documents/2023/01/26/AI%20RMF%20Playbook.pdf"),
    ("iso-iec-42001", "ISO/IEC 42001 AI Management System",
     "governance-risk", "frameworks",
     "International standard for AI management systems.",
     "https://www.iso.org/standard/81230.html"),
    ("iso-iec-23894", "ISO/IEC 23894:2023 AI Risk Management",
     "governance-risk", "frameworks",
     "Guidance on risk management for AI systems.",
     "https://www.iso.org/standard/77304.html"),
    ("google-saif", "Google Secure AI Framework (SAIF)",
     "governance-risk", "frameworks",
     "Google's framework for securing AI systems.",
     "https://safety.google/cybersecurity-advancements/saif/"),
    ("enisa-ai-framework", "ENISA Multilayer AI Cybersecurity Framework",
     "governance-risk", "frameworks",
     "ENISA framework for good cybersecurity practices for AI.",
     "https://www.enisa.europa.eu/publications/multilayer-framework-for-good-cybersecurity-practices-for-ai"),
    ("owasp-ai-maturity", "OWASP AI Maturity Assessment",
     "governance-risk", "frameworks",
     "OWASP tool for assessing AI security maturity.",
     "https://owasp.org/www-project-artificial-intelligence-maturity-assessment/"),
    ("csa-ai-model-risk", "CSA AI Model Risk Framework",
     "governance-risk", "frameworks",
     "Cloud Security Alliance framework for AI model risk.",
     "https://cloudsecurityalliance.org/research/topics/artificial-intelligence"),
    ("csa-maestro", "CSA Maestro AI Threat Modeling Framework",
     "governance-risk", "frameworks",
     "CSA's threat modeling framework for AI systems.",
     "https://cloudsecurityalliance.org/research/topics/artificial-intelligence"),
    ("csa-ai-controls-matrix", "CSA AI Controls Matrix",
     "governance-risk", "frameworks",
     "Comprehensive controls matrix for AI systems covering governance, risk, and compliance.",
     "https://cloudsecurityalliance.org/research/topics/artificial-intelligence"),
    ("owasp-asvs-ai", "OWASP AI Security Verification Standard",
     "governance-risk", "standards",
     "Standard for verifying security of AI/ML systems.",
     "https://owasp.org/www-project-ai-security-verification-standard/"),
    ("owasp-agent-name-service", "OWASP Agent Name Service",
     "governance-risk", "standards",
     "OWASP standard for agent naming and identity.",
     "https://owasp.org/www-project-agent-name-service/"),
    ("owasp-agent-observability", "OWASP Agent Observability Standard",
     "governance-risk", "standards",
     "OWASP standard for AI agent observability.",
     "https://owasp.org/www-project-agentic-ai-threats-and-mitigations/"),
    ("ai-verify", "AI Verify",
     "governance-risk", "standards",
     "Singapore government-backed AI testing framework for verifying AI system properties.",
     "https://aiverifyfoundation.sg/"),
    ("nist-ai-100-2", "NIST AI 100-2e2023 Adversarial ML Taxonomy",
     "governance-risk", "taxonomies",
     "Adversarial machine learning taxonomy and terminology from NIST.",
     "https://airc.nist.gov/Publications/1"),
    ("mitre-atlas", "MITRE ATLAS",
     "governance-risk", "taxonomies",
     "Adversarial Threat Landscape for Artificial-Intelligence Systems — MITRE's knowledge base for ML attack techniques.",
     "https://atlas.mitre.org/"),
    ("avidml", "AVIDML",
     "governance-risk", "taxonomies",
     "AI Vulnerability Database for tracking AI/ML vulnerabilities.",
     "https://avidml.org/"),
    ("mit-ai-risk-repo", "MIT AI Risk Repository",
     "governance-risk", "taxonomies",
     "MIT's comprehensive repository of AI risks.",
     "https://airisk.mit.edu/"),
    ("ai-incident-database", "AI Incident Database",
     "governance-risk", "taxonomies",
     "Database of AI incidents to learn from failures.",
     "https://incidentdatabase.ai/"),
    ("arcanum-prompt-injection-taxonomy", "Arcanum Prompt Injection Taxonomy",
     "governance-risk", "taxonomies",
     "Comprehensive prompt injection attack classification covering intents, techniques, evasions, and input vectors.",
     "https://arcanum.security/taxonomy"),
    ("csa-llm-threats-taxonomy", "CSA LLM Threats Taxonomy",
     "governance-risk", "taxonomies",
     "Cloud Security Alliance taxonomy of LLM threats.",
     "https://cloudsecurityalliance.org/research/topics/artificial-intelligence"),
    ("owasp-aivss", "OWASP AI Vulnerability Scoring System (AIVSS)",
     "governance-risk", "taxonomies",
     "Scoring system for AI-specific vulnerabilities extending CVSS to AI risk dimensions.",
     "https://owasp.org/www-project-ai-vulnerability-scoring-system/"),
    ("owasp-llm-checklist", "OWASP LLM Applications Governance Checklist",
     "governance-risk", "checklists",
     "Cybersecurity and governance checklist for LLM applications.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),
    ("owasp-agentic-threats", "OWASP Agentic AI – Threats and Mitigations",
     "governance-risk", "checklists",
     "OWASP guidance on agentic AI threats and corresponding mitigations.",
     "https://owasp.org/www-project-agentic-ai-threats-and-mitigations/"),
    ("owasp-genai-incident-response", "OWASP GenAI Incident Response Guide",
     "governance-risk", "checklists",
     "OWASP guide for responding to generative AI security incidents.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),
    ("owasp-securing-agentic", "OWASP Securing Agentic AI Applications",
     "governance-risk", "checklists",
     "OWASP guide for securing agentic AI applications.",
     "https://owasp.org/www-project-agentic-ai-threats-and-mitigations/"),
    ("owasp-genai-red-teaming", "OWASP GenAI Red Teaming Guide",
     "governance-risk", "checklists",
     "OWASP guide for red teaming generative AI applications.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),

    # ── Attack Techniques & Red Teaming ────────────────────────────────────
    ("adversarial-robustness-toolkit", "Adversarial Robustness Toolkit (ART)",
     "attack-red-teaming", "adversarial-ml",
     "IBM library covering evasion, poisoning, extraction, and inference attacks on ML models.",
     "https://github.com/Trusted-AI/adversarial-robustness-toolbox"),
    ("cleverhans", "cleverhans",
     "attack-red-teaming", "adversarial-ml",
     "Adversarial example library for constructing attacks, building defenses, and benchmarking.",
     "https://github.com/cleverhans-lab/cleverhans"),
    ("foolbox", "foolbox",
     "attack-red-teaming", "adversarial-ml",
     "Python toolbox to create adversarial examples for PyTorch, TensorFlow, and JAX models.",
     "https://github.com/bethgelab/foolbox"),
    ("textattack", "TextAttack",
     "attack-red-teaming", "adversarial-ml",
     "Python framework for adversarial attacks, data augmentation, and model training in NLP.",
     "https://github.com/QData/TextAttack"),
    ("counterfit", "Counterfit",
     "attack-red-teaming", "adversarial-ml",
     "Microsoft generic automation layer for assessing security of machine learning systems.",
     "https://github.com/Azure/counterfit"),
    ("offsecml-playbook", "OffsecML Playbook",
     "attack-red-teaming", "adversarial-ml",
     "Collection of offensive and adversarial TTPs with proofs of concept for ML systems.",
     "https://wiki.offsecml.com/"),
    ("snaike-mlflow", "Snaike-MLFlow",
     "attack-red-teaming", "adversarial-ml",
     "MLflow red team toolsuite for attacking ML pipelines.",
     "https://github.com/protectai/snaike-mlflow"),
    ("garak", "garak",
     "attack-red-teaming", "llm-red-teaming",
     "Security probing tool for LLMs — tests for prompt injection, jailbreaks, hallucination, and more.",
     "https://github.com/leondz/garak"),
    ("ai-scanner", "ai-scanner",
     "attack-red-teaming", "llm-red-teaming",
     "Open-source web app for AI model security assessments on NVIDIA garak. 179 probes, multi-target scanning, ASR scoring, SIEM integration.",
     "https://github.com/mindgard/ai-scanner"),
    ("promptfoo", "promptfoo",
     "attack-red-teaming", "llm-red-teaming",
     "Test prompts, agents, and RAGs. Red teaming, pentesting, and vulnerability scanning for LLMs. Supports GPT, Claude, Gemini, Llama, and more.",
     "https://github.com/promptfoo/promptfoo"),
    ("pyrit", "PyRIT",
     "attack-red-teaming", "llm-red-teaming",
     "Microsoft's Python Risk Identification Tool for generative AI — proactively identifies risks in GenAI systems.",
     "https://github.com/Azure/PyRIT"),
    ("purplellama", "PurpleLlama",
     "attack-red-teaming", "llm-red-teaming",
     "Meta's set of tools to assess and improve LLM security.",
     "https://github.com/meta-llama/PurpleLlama"),
    ("augustus", "augustus",
     "attack-red-teaming", "llm-red-teaming",
     "LLM security testing framework: 190+ probes, 28 providers, single Go binary. Detects prompt injection, jailbreaks, adversarial attacks.",
     "https://github.com/augustuslabs/augustus"),
    ("fuzzyai", "FuzzyAI",
     "attack-red-teaming", "llm-red-teaming",
     "Automated LLM fuzzing tool for identifying and mitigating jailbreaks in LLM APIs.",
     "https://github.com/cyberark/FuzzyAI"),
    ("llmfuzzer", "LLMFuzzer",
     "attack-red-teaming", "llm-red-teaming",
     "First open-source fuzzing framework specifically designed for LLMs and their API integrations.",
     "https://github.com/mnns/LLMFuzzer"),
    ("easyjailbreak", "EasyJailbreak",
     "attack-red-teaming", "llm-red-teaming",
     "Python framework for generating adversarial jailbreak prompts against LLMs.",
     "https://github.com/EasyJailbreak/EasyJailbreak"),
    ("gptfuzz", "gptfuzz",
     "attack-red-teaming", "llm-red-teaming",
     "Auto-generated jailbreak prompts framework — GPTFUZZER red teaming for LLMs.",
     "https://github.com/sherdencooper/GPTFuzz"),
    ("agentic-security", "agentic_security",
     "attack-red-teaming", "llm-red-teaming",
     "Agentic LLM vulnerability scanner and AI red teaming kit.",
     "https://github.com/msoedov/agentic_security"),
    ("agentic-radar", "Agentic Radar",
     "attack-red-teaming", "llm-red-teaming",
     "Open-source CLI security scanner for agentic workflows.",
     "https://github.com/splxsg/agentic-radar"),
    ("raptor", "RAPTOR",
     "attack-red-teaming", "llm-red-teaming",
     "Autonomous offensive/defensive security research framework on Claude Code. Chains Semgrep, CodeQL, binary analysis, LLM validation, exploit generation, and patch writing.",
     "https://github.com/harishsg993010/RAPTOR"),
    ("whistleblower", "whistleblower",
     "attack-red-teaming", "llm-red-teaming",
     "Offensive tool for testing system prompt leakage and capability discovery of AI applications.",
     "https://github.com/Martian-Engineering/whistleblower"),
    ("promptmap", "promptmap",
     "attack-red-teaming", "llm-red-teaming",
     "Prompt injection scanner for custom LLM applications.",
     "https://github.com/utkusen/promptmap"),
    ("houyi", "HouYi",
     "attack-red-teaming", "llm-red-teaming",
     "Automated prompt injection framework for LLM-integrated applications.",
     "https://github.com/LasCC/HouYi"),
    ("spikee", "spikee",
     "attack-red-teaming", "llm-red-teaming",
     "Simple Prompt Injection Kit for Evaluation and Exploitation.",
     "https://github.com/withsecurelabs/spikee"),
    ("ps-fuzz", "ps-fuzz",
     "attack-red-teaming", "llm-red-teaming",
     "Test and harden system prompts — makes GenAI apps safe and secure.",
     "https://github.com/prompt-security/ps-fuzz"),
    ("mcp-injection-experiments", "mcp-injection-experiments",
     "attack-red-teaming", "agentic-mcp-attacks",
     "Code snippets to reproduce MCP tool poisoning attacks.",
     "https://github.com/harishsg993010/mcp-injection-experiments"),
    ("rampart", "RAMPART",
     "attack-red-teaming", "agentic-mcp-attacks",
     "pytest-native safety and security testing framework for agentic AI applications.",
     "https://github.com/harishsg993010/RAMPART"),
    ("ai-infra-guard", "AI-Infra-Guard",
     "attack-red-teaming", "agentic-mcp-attacks",
     "Tencent Zhuque Lab AI red teaming platform with Infra Scan, MCP Scan, and Jailbreak Evaluation.",
     "https://github.com/Tencent/AI-Infra-Guard"),
    ("openpromptinjection", "OpenPromptInjection",
     "attack-red-teaming", "agentic-mcp-attacks",
     "Benchmark for prompt injection attacks and defenses in LLM-integrated applications.",
     "https://github.com/liu00222/Open-Prompt-Injection"),
    ("pentestgpt", "PentestGPT",
     "attack-red-teaming", "ai-assisted-offensive",
     "GPT-empowered penetration testing tool for AI-assisted security assessments.",
     "https://github.com/GreyDGL/PentestGPT"),
    ("hackingbuddygpt", "HackingBuddyGPT",
     "attack-red-teaming", "ai-assisted-offensive",
     "LLM-powered ethical hacking assistant in 50 lines of code or less.",
     "https://github.com/ipa-lab/hackingBuddyGPT"),
    ("cyberstrike-ai", "CyberStrikeAI",
     "attack-red-teaming", "ai-assisted-offensive",
     "AI-native security testing platform in Go. 100+ tools, intelligent orchestration, role-based testing, MCP protocol, full lifecycle automation.",
     "https://github.com/harishsg993010/CyberStrikeAI"),
    ("hexstrike-ai", "HexStrikeAI",
     "attack-red-teaming", "ai-assisted-offensive",
     "MCP server letting AI agents autonomously run 150+ cybersecurity tools for automated pentesting and bug bounty.",
     "https://github.com/harishsg993010/HexStrikeAI"),
    ("mcp-for-security", "mcp-for-security",
     "attack-red-teaming", "ai-assisted-offensive",
     "MCP servers for SQLMap, FFUF, NMAP, Masscan and more — integrate security tools into AI workflows.",
     "https://github.com/fr0gger/mcp-for-security"),
    ("mcp-security-hub", "mcp-security-hub",
     "attack-red-teaming", "ai-assisted-offensive",
     "Collection of MCP servers: Nmap, Ghidra, Nuclei, SQLMap, Hashcat and more for AI assistants.",
     "https://github.com/harishsg993010/mcp-security-hub"),
    ("burpgpt", "burpgpt",
     "attack-red-teaming", "ai-assisted-offensive",
     "Burp Suite extension integrating GPT for passive scanning and traffic-based vulnerability analysis.",
     "https://github.com/aress31/burpgpt"),
    ("guardian-cli", "guardian-cli",
     "attack-red-teaming", "ai-assisted-offensive",
     "AI-powered security testing and vulnerability scanner automating penetration testing and security auditing.",
     "https://github.com/harishsg993010/guardian-cli"),
    ("auto-pentest-x", "AutoPentestX",
     "attack-red-teaming", "ai-assisted-offensive",
     "Linux automated pentesting and vulnerability reporting tool.",
     "https://github.com/harishsg993010/AutoPentestX"),
    ("clearwing", "clearwing",
     "attack-red-teaming", "ai-assisted-offensive",
     "Autonomous vulnerability scanner and source-code hunter built on LangGraph.",
     "https://github.com/harishsg993010/clearwing"),
    ("zen-ai-pentest", "Zen-AI-Pentest",
     "attack-red-teaming", "ai-assisted-offensive",
     "AI-powered penetration testing framework: 72+ security tools, Docker sandbox, ReAct agents, attack path analysis.",
     "https://github.com/harishsg993010/Zen-AI-Pentest"),

    # ── Benchmarks & Evaluations ───────────────────────────────────────────
    ("jailbreakbench", "JailbreakBench",
     "benchmarks-evals", "benchmarks",
     "Open robustness benchmark for jailbreaking language models (NeurIPS 2024).",
     "https://github.com/JailbreakBench/jailbreakbench"),
    ("agentdojo", "AgentDojo",
     "benchmarks-evals", "benchmarks",
     "Dynamic environment to evaluate attacks and defenses for LLM agents.",
     "https://github.com/ethz-spylab/agentdojo"),
    ("airtbench", "AIRTBench",
     "benchmarks-evals", "benchmarks",
     "Benchmark measuring autonomous AI red teaming capabilities in language models.",
     "https://github.com/harishsg993010/AIRTBench"),
    ("hackingbuddygpt-benchmark", "HackingBuddyGPT Benchmark Dataset",
     "benchmarks-evals", "benchmarks",
     "Benchmark dataset for automated LLM-assisted pentesting.",
     "https://github.com/ipa-lab/hackingBuddyGPT"),
    ("agentdog", "AgentDoG",
     "benchmarks-evals", "benchmarks",
     "Risk-aware evaluation and guarding framework for autonomous agents — trajectory-level risk assessment.",
     "https://github.com/harishsg993010/AgentDoG"),

    # ── Defense & Security Controls: Input/Output Guardrails ───────────────
    ("nemo-guardrails", "NeMo-Guardrails",
     "defense-controls", "io-guardrails",
     "NVIDIA open-source toolkit for adding programmable guardrails to LLM-based conversational systems.",
     "https://github.com/NVIDIA/NeMo-Guardrails"),
    ("llamafirewall", "LlamaFirewall",
     "defense-controls", "io-guardrails",
     "Meta framework to detect and mitigate AI-centric security risks across LLM chat and multi-step agentic operations.",
     "https://github.com/meta-llama/LlamaFirewall"),
    ("llm-guard", "llm-guard",
     "defense-controls", "io-guardrails",
     "Protect AI's comprehensive tool for fortifying LLM security — input/output scanning.",
     "https://github.com/protectai/llm-guard"),
    ("guardrails-ai", "Guardrails.ai",
     "defense-controls", "io-guardrails",
     "Python package for adding structure, type, and quality guarantees to LLM outputs.",
     "https://github.com/guardrails-ai/guardrails"),
    ("trustgate", "TrustGate",
     "defense-controls", "io-guardrails",
     "Generative Application Firewall (GAF) to detect, prevent, and block attacks against GenAI applications.",
     "https://github.com/intelligencepack/trustgate"),
    ("zenguard-ai", "ZenGuard AI",
     "defense-controls", "io-guardrails",
     "Fastest Trust Layer for AI Agents — real-time guardrails.",
     "https://www.zenguard.ai/"),
    ("vibraniumdome", "vibraniumdome",
     "defense-controls", "io-guardrails",
     "End-to-end LLM WAF for agents with governance, auditing, and policy-driven control over LLM usage.",
     "https://github.com/genia-dev/vibraniumdome"),
    ("localmod", "LocalMod",
     "defense-controls", "io-guardrails",
     "Self-hosted content moderation API with prompt injection detection, toxicity filtering, PII detection. 100% offline.",
     "https://github.com/harishsg993010/LocalMod"),
    ("safe-zone", "Safe Zone",
     "defense-controls", "io-guardrails",
     "Open-source PII detection and guardrails engine preventing sensitive data from reaching LLMs and third-party APIs.",
     "https://github.com/harishsg993010/safe-zone"),
    ("shellward", "ShellWard",
     "defense-controls", "io-guardrails",
     "AI agent security middleware with 8-layer defense: prompt injection, data exfiltration, dangerous commands. Zero dependencies.",
     "https://github.com/harishsg993010/ShellWard"),
    ("rebuff", "rebuff",
     "defense-controls", "io-guardrails",
     "Prompt injection detector for LLM applications.",
     "https://github.com/protectai/rebuff"),
    ("langkit", "langkit",
     "defense-controls", "io-guardrails",
     "Open-source text metrics toolkit for monitoring language models including security-related metrics.",
     "https://github.com/whylabs/langkit"),
    ("codegate", "CodeGate",
     "defense-controls", "io-guardrails",
     "Privacy-focused security layer for AI code generation workflows.",
     "https://github.com/stacklok/codegate"),

    # ── Defense: Agent Runtime Security & Sandboxing ───────────────────────
    ("openshell", "OpenShell",
     "defense-controls", "agent-runtime-sandbox",
     "Safe, private runtime for autonomous AI agents with declarative YAML policies controlling file access, data exfiltration, and network activity.",
     "https://github.com/harishsg993010/OpenShell"),
    ("opensandbox", "OpenSandbox",
     "defense-controls", "agent-runtime-sandbox",
     "Secure, extensible sandbox runtime for AI agents. Multi-language SDKs, Docker/Kubernetes, gVisor/Kata/Firecracker isolation. CNCF Landscape project.",
     "https://github.com/harishsg993010/opensandbox"),
    ("cubesandbox", "CubeSandbox",
     "defense-controls", "agent-runtime-sandbox",
     "Tencent Cloud instant, secure, lightweight sandbox for AI agents. Sub-60ms cold start, <5MB overhead, built on RustVMM + KVM.",
     "https://github.com/harishsg993010/CubeSandbox"),
    ("aegis-edr", "Aegis",
     "defense-controls", "agent-runtime-sandbox",
     "Open-source EDR for AI agents. Monitor processes, files, network, and behavior of autonomous AI agents in real time.",
     "https://github.com/harishsg993010/Aegis"),
    ("microsoft-agent-governance", "Microsoft Agent Governance Toolkit",
     "defense-controls", "agent-runtime-sandbox",
     "Policy enforcement, zero-trust identity, execution sandboxing, and reliability engineering for autonomous AI agents. Covers OWASP Agentic Top 10.",
     "https://github.com/microsoft/agent-governance-toolkit"),
    ("agentfield", "agentfield",
     "defense-controls", "agent-runtime-sandbox",
     "Open-source control plane for agent systems with cryptographic identity, policy enforcement, and audit-friendly observability.",
     "https://github.com/harishsg993010/agentfield"),
    ("leash", "leash",
     "defense-controls", "agent-runtime-sandbox",
     "Wraps AI coding agents in containers and monitors their activity.",
     "https://github.com/harishsg993010/leash"),
    ("vibekit", "vibekit",
     "defense-controls", "agent-runtime-sandbox",
     "Run Claude Code, Gemini, Codex in a clean isolated sandbox with sensitive data redaction and observability.",
     "https://github.com/harishsg993010/vibekit"),
    ("pipelock", "pipelock",
     "defense-controls", "agent-runtime-sandbox",
     "Security harness for AI agents — egress proxy with DLP scanning, SSRF protection, MCP response scanning, and workspace integrity monitoring.",
     "https://github.com/harishsg993010/pipelock"),
    ("skill-scanner", "skill-scanner",
     "defense-controls", "agent-runtime-sandbox",
     "Security scanner for AI Agent Skills detecting prompt injection, data exfiltration, and malicious code. Combines pattern-based (YAML + YARA), LLM-as-a-judge, and behavioral analysis.",
     "https://github.com/harishsg993010/skill-scanner"),
    ("project-codeguard", "Project CodeGuard",
     "defense-controls", "agent-runtime-sandbox",
     "CoSAI open source project for securing AI-assisted development. Security controls and guardrails preventing vulnerabilities in AI-generated code.",
     "https://github.com/harishsg993010/CodeGuard"),
    ("agentlens", "AgentLens",
     "defense-controls", "agent-runtime-sandbox",
     "Agent observability and replay tooling for AI safety and interpretability research. Captures trajectories in ATIF format.",
     "https://github.com/harishsg993010/AgentLens"),
    ("claude-code-devcontainer", "claude-code-devcontainer",
     "defense-controls", "agent-runtime-sandbox",
     "Sandboxed devcontainer for running Claude Code in bypass mode safely — built for security audits.",
     "https://github.com/harishsg993010/claude-code-devcontainer"),
    ("claude-code-safety-net", "claude-code-safety-net",
     "defense-controls", "agent-runtime-sandbox",
     "Claude Code plugin catching destructive git and filesystem commands before they execute.",
     "https://github.com/harishsg993010/claude-code-safety-net"),
    ("onecli-vault", "OneCLI",
     "defense-controls", "agent-runtime-sandbox",
     "Open-source credential vault for AI agents. Rust HTTP gateway injects API credentials transparently — agents never hold raw keys. AES-256-GCM, per-agent scoping, full audit trail.",
     "https://github.com/harishsg993010/OneCLI"),
    ("microsandbox", "microsandbox",
     "defense-controls", "agent-runtime-sandbox",
     "Lightweight microVM sandbox for running untrusted AI-generated code with strong isolation.",
     "https://github.com/harishsg993010/microsandbox"),

    # ── Defense: MCP Security ──────────────────────────────────────────────
    ("mcp-security-checklist", "MCP Security Checklist",
     "defense-controls", "mcp-security",
     "Comprehensive security checklist for MCP-based AI tools by SlowMist.",
     "https://github.com/slowmist/MCP-Security-Checklist"),
    ("awesome-mcp-security", "Awesome-MCP-Security",
     "defense-controls", "mcp-security",
     "Everything you need to know about MCP security.",
     "https://github.com/harishsg993010/awesome-mcp-security"),
    ("secure-mcp-gateway", "secure-mcp-gateway",
     "defense-controls", "mcp-security",
     "Secure MCP Gateway with authentication, automatic tool discovery, caching, and guardrail enforcement.",
     "https://github.com/harishsg993010/secure-mcp-gateway"),
    ("mcp-context-protector", "mcp-context-protector",
     "defense-controls", "mcp-security",
     "Security wrapper for MCP servers addressing line jumping, unexpected server config changes, and prompt injection attacks.",
     "https://github.com/harishsg993010/mcp-context-protector"),
    ("mcp-guardian", "mcp-guardian",
     "defense-controls", "mcp-security",
     "Manages LLM assistant access to MCP servers with real-time activity control.",
     "https://github.com/harishsg993010/mcp-guardian"),
    ("mcp-scan", "MCP-Scan",
     "defense-controls", "mcp-security",
     "Security scanning tool for MCP servers detecting prompt injection and tool poisoning.",
     "https://github.com/harishsg993010/MCP-Scan"),
    ("atr-agent-threat-rules", "ATR (Agent Threat Rules)",
     "defense-controls", "mcp-security",
     "108 regex rules covering prompt injection, tool poisoning, credential exfiltration across 9 categories. Used by Cisco AI Defense. MIT licensed.",
     "https://github.com/harishsg993010/ATR"),
    ("mcpproxy", "MCPProxy",
     "defense-controls", "mcp-security",
     "Local-first MCP proxy with SHA-256 quarantine, sensitive-data scanning, Docker sandbox isolation for untrusted MCP servers, OAuth 2.1. MIT licensed.",
     "https://github.com/harishsg993010/MCPProxy"),

    # ── Defense: Model & Artifact Scanning ─────────────────────────────────
    ("modelscan", "modelscan",
     "defense-controls", "model-scanning",
     "Protect AI's open source scanner for ML model files detecting unsafe code.",
     "https://github.com/protectai/modelscan"),
    ("picklescan", "picklescan",
     "defense-controls", "model-scanning",
     "Security scanner detecting Python Pickle files performing suspicious actions.",
     "https://github.com/mmaitre314/picklescan"),
    ("fickling", "fickling",
     "defense-controls", "model-scanning",
     "Python pickling decompiler and static analyzer for detecting malicious pickle payloads.",
     "https://github.com/trailofbits/fickling"),
    ("medusa-ai-scanner", "medusa",
     "defense-controls", "model-scanning",
     "AI-first security scanner: 74+ analyzers, 180+ AI agent security rules, intelligent false positive reduction. All languages, CVE detection.",
     "https://github.com/harishsg993010/medusa"),
    ("julius-llm-fingerprint", "julius",
     "defense-controls", "model-scanning",
     "LLM service fingerprinting tool detecting 32+ AI services (Ollama, vLLM, LiteLLM, HF TGI) during penetration tests.",
     "https://github.com/harishsg993010/julius"),
    ("a2a-scanner", "a2a-scanner",
     "defense-controls", "model-scanning",
     "Scan A2A agents for potential threats and security issues.",
     "https://github.com/harishsg993010/a2a-scanner"),

    # ── Defense: AI-Assisted Defensive Security ────────────────────────────
    ("claude-code-security-review", "Claude Code Security Review",
     "defense-controls", "ai-assisted-defense",
     "AI-powered security review GitHub Action using Claude to analyze code changes for vulnerabilities.",
     "https://github.com/harishsg993010/claude-code-security-review"),
    ("deepsec", "deepsec",
     "defense-controls", "ai-assisted-defense",
     "Vercel Labs agent-powered vulnerability scanner for hard-to-spot issues in large codebases. Supports parallel scanning and PR diff review.",
     "https://github.com/vercel/deepsec"),
    ("defending-code-reference-harness", "defending-code-reference-harness",
     "defense-controls", "ai-assisted-defense",
     "Reference implementation for autonomous vulnerability discovery and remediation using Claude. Includes threat modeling, scanning, triage, and patching skills.",
     "https://github.com/harishsg993010/defending-code-reference-harness"),
    ("ghidragpt", "GhidraGPT",
     "defense-controls", "ai-assisted-defense",
     "GPT integration into Ghidra for automated code analysis, variable renaming, vulnerability detection, and explanation.",
     "https://github.com/harishsg993010/GhidraGPT"),
    ("idassist", "IDAssist",
     "defense-controls", "ai-assisted-defense",
     "AI-powered reverse engineering plugin for IDA Pro. LLM-powered analysis with semantic knowledge graphs, RAG, multi-provider support.",
     "https://github.com/harishsg993010/IDAssist"),
    ("threatforest", "ThreatForest",
     "defense-controls", "ai-assisted-defense",
     "Agentic threat modeling platform on Strands. Autonomously generates attack trees, maps to MITRE ATT&CK, produces mitigation recommendations.",
     "https://github.com/harishsg993010/ThreatForest"),
    ("claude-grc-plugin", "claude-grc-plugin",
     "defense-controls", "ai-assisted-defense",
     "Claude Code plugin for GRC work. 72+ reference files covering 15 frameworks (NIST 800-53, FedRAMP, ISO 27001, SOC 2). 24 slash commands.",
     "https://github.com/harishsg993010/claude-grc-plugin"),
    ("vigil-soc", "Vigil SOC",
     "defense-controls", "ai-assisted-defense",
     "Comprehensive open-source security operations platform for AI agents — real-time monitoring, threat detection, incident response.",
     "https://github.com/harishsg993010/vigil-soc"),
    ("aisoc", "AiSOC",
     "defense-controls", "ai-assisted-defense",
     "Open-source self-hostable AI SOC. Ingests security events, correlates, runs autonomous LangGraph investigations. 52 connectors, MIT licensed.",
     "https://github.com/harishsg993010/AiSOC"),

    # ── Defense: Privacy & Confidential Computing ──────────────────────────
    ("diffprivlib", "Diffprivlib",
     "defense-controls", "privacy",
     "IBM Differential Privacy Library for building privacy-preserving ML pipelines.",
     "https://github.com/IBM/differential-privacy-library"),
    ("tenseal", "TenSEAL",
     "defense-controls", "privacy",
     "Library for homomorphic encryption operations on tensors.",
     "https://github.com/OpenMined/TenSEAL"),
    ("cloaked-ai", "Cloaked AI",
     "defense-controls", "privacy",
     "Open source property-preserving encryption for vector embeddings.",
     "https://github.com/harishsg993010/cloaked-ai"),
    ("dstack", "dstack",
     "defense-controls", "privacy",
     "Open-source confidential AI framework for secure ML/LLM deployment with hardware-enforced isolation.",
     "https://github.com/dstackai/dstack"),
    ("privacyraven", "PrivacyRaven",
     "defense-controls", "privacy",
     "Privacy testing library for deep learning systems.",
     "https://github.com/trailofbits/PrivacyRaven"),
    ("plot4ai", "PLOT4ai",
     "defense-controls", "privacy",
     "Privacy Library Of Threats 4 Artificial Intelligence — threat modeling library for responsible AI.",
     "https://plot4.ai/"),
    ("opendp", "OpenDP",
     "defense-controls", "privacy",
     "Core library for differential privacy algorithms — used to build privacy-preserving ML training pipelines.",
     "https://github.com/opendp/opendp"),

    # ── Defense: Data & Supply Chain Security ─────────────────────────────
    ("datasig", "datasig",
     "defense-controls", "data-supply-chain",
     "Dataset fingerprinting for AI Bill of Materials (AIBOM).",
     "https://github.com/harishsg993010/datasig"),
    ("owasp-aibom", "OWASP AIBOM",
     "defense-controls", "data-supply-chain",
     "OWASP AI Bill of Materials standard.",
     "https://owasp.org/www-project-ai-bill-of-materials/"),
    ("trusera-ai-bom", "Trusera ai-bom",
     "defense-controls", "data-supply-chain",
     "AI Bill of Materials — discover every AI agent, model, and API in your infrastructure.",
     "https://github.com/harishsg993010/ai-bom"),

    # ── Agentic AI Security Skills ─────────────────────────────────────────
    ("elastic-agent-skills", "Elastic Agent Skills",
     "agentic-skills", "skill-collections",
     "Skills for Elastic's AI assistant enabling natural language security investigations across logs, traces, and threat intelligence.",
     "https://github.com/elastic/elastic-agent-skills"),
    ("ghost-security-skills", "Ghost Security Skills",
     "agentic-skills", "skill-collections",
     "Agent application security (appsec) skills and tools for Claude Code.",
     "https://github.com/ghostsecurity/skills"),
    ("tm-skills", "tm_skills",
     "agentic-skills", "skill-collections",
     "Agent skills for Continuous Threat Modeling.",
     "https://github.com/harishsg993010/tm_skills"),
    ("trail-of-bits-skills", "Trail of Bits Skills Marketplace",
     "agentic-skills", "skill-collections",
     "Trail of Bits Claude Code skills for security research, vulnerability detection, and audit workflows.",
     "https://github.com/trailofbits/toby"),
    ("semgrep-skills", "Semgrep Skills",
     "agentic-skills", "skill-collections",
     "Official Semgrep skills for Claude Code and AI coding assistants. Security scanning, code analysis, vulnerability detection in AI workflows.",
     "https://github.com/semgrep/semgrep-skills"),
    ("claude-bug-bounty", "claude-bug-bounty",
     "agentic-skills", "skill-collections",
     "Claude Code skill for AI-assisted bug bounty. Automates recon, IDOR, XSS, SSRF, OAuth, GraphQL, LLM injection testing with 4-gate validation.",
     "https://github.com/harishsg993010/claude-bug-bounty"),
    ("anthropic-cybersecurity-skills", "Anthropic Cybersecurity Skills",
     "agentic-skills", "skill-collections",
     "734+ structured cybersecurity skills for AI agents. MITRE ATT&CK mapped, agentskills.io standard. Compatible with Claude Code, Copilot, Codex CLI, Cursor, Gemini CLI.",
     "https://github.com/mukul975/Anthropic-Cybersecurity-Skills"),
    ("llm-sast-scanner", "llm-sast-scanner",
     "agentic-skills", "skill-collections",
     "SAST skill for AI coding agents with vulnerability detection across 34 classes. Source-to-sink taint analysis, Judge verification for false positive reduction.",
     "https://github.com/harishsg993010/llm-sast-scanner"),
    ("sast-skills", "sast-skills",
     "agentic-skills", "skill-collections",
     "Collection of agent skills turning your AI coder into a SAST scanner.",
     "https://github.com/harishsg993010/sast-skills"),
    ("pentest-ai-agents", "pentest-ai-agents",
     "agentic-skills", "skill-collections",
     "31 Claude Code subagents for offensive security: recon, web, AD, cloud, mobile, wireless, social engineering, forensics, and report generation.",
     "https://github.com/harishsg993010/pentest-ai-agents"),

    # ── Security-Focused AI Models ─────────────────────────────────────────
    ("vulnllm-r-7b", "VulnLLM-R-7B",
     "security-ai-models", "vulnerability-detection",
     "Specialized reasoning LLM for vulnerability detection. CoT reasoning for data/control flow analysis. Outperforms Claude-3.7-Sonnet on benchmarks.",
     "https://huggingface.co/harishsg993010/VulnLLM-R-7B"),
    ("foundation-sec-8b", "Foundation-Sec-8B-Reasoning",
     "security-ai-models", "vulnerability-detection",
     "Llama-3.1-based 8B instruction-tuned model specialized for cybersecurity applications with instruction-following and reasoning.",
     "https://huggingface.co/fdtn-ai/Foundation-Sec-8B"),
    ("cybersecqwen-4b", "CyberSecQwen-4B",
     "security-ai-models", "vulnerability-detection",
     "4B-parameter CTI specialist fine-tuned from Qwen3-4B for cybersecurity threat intelligence.",
     "https://huggingface.co/harishsg993010/CyberSecQwen-4B"),
    ("llama-guard-4", "Llama-Guard-4-12B",
     "security-ai-models", "safety-classifiers",
     "Meta's latest multimodal safety classifier for harmful content in LLM inputs and outputs across text and image.",
     "https://huggingface.co/meta-llama/Llama-Guard-4-12B"),
    ("llama-prompt-guard-2", "Llama-Prompt-Guard-2-86M",
     "security-ai-models", "safety-classifiers",
     "Lightweight 86M parameter Meta model for detecting prompt injection and jailbreak attempts in production LLM pipelines.",
     "https://huggingface.co/meta-llama/Llama-Prompt-Guard-2-86M"),
    ("shieldgemma-2b", "ShieldGemma-2B",
     "security-ai-models", "safety-classifiers",
     "Google's 2B parameter text safety classifier for harmful content detection, built on Gemma architecture.",
     "https://huggingface.co/google/shieldgemma-2b"),
    ("deberta-prompt-injection", "DeBERTa Prompt Injection Detector v2",
     "security-ai-models", "safety-classifiers",
     "Protect AI's DeBERTa-v3-base fine-tuned for prompt injection detection, widely used in production guardrail pipelines.",
     "https://huggingface.co/protectai/deberta-v3-base-prompt-injection-v2"),
    ("prompt-injection-sentinel", "Prompt Injection Sentinel",
     "security-ai-models", "safety-classifiers",
     "ModernBERT-large model fine-tuned for prompt injection and jailbreak classification with low false-positive rate.",
     "https://huggingface.co/harishsg993010/prompt-injection-sentinel"),
    ("nemotron-content-safety", "Nemotron 3.5 Content Safety",
     "security-ai-models", "safety-classifiers",
     "NVIDIA's 4B multimodal content safety model: text+image, 35+ languages, customizable enterprise policy, auditable reasoning.",
     "https://huggingface.co/nvidia/Nemotron-3.5-Content-Safety"),
    ("browsesafe", "BrowseSafe",
     "security-ai-models", "safety-classifiers",
     "Specialized model detecting prompt injection in AI browser agents. 90.4% F1 on BrowseSafe-Bench, optimized for real-time HTML content classification.",
     "https://huggingface.co/harishsg993010/BrowseSafe"),
    ("attack-bert", "ATTACK-BERT",
     "security-ai-models", "domain-models",
     "Sentence-transformer model for mapping security text to MITRE ATT&CK techniques.",
     "https://huggingface.co/harishsg993010/ATTACK-BERT"),

    # ── Datasets ───────────────────────────────────────────────────────────
    ("safetyprompts", "SafetyPrompts",
     "datasets", "safety-evals",
     "Curated collection of safety-relevant prompts for evaluating LLM safety and security properties.",
     "https://github.com/harishsg993010/SafetyPrompts"),
    ("do-not-answer", "Do-Not-Answer",
     "datasets", "safety-evals",
     "Dataset of prompts that responsible LLMs should not answer — for safety evaluation and red teaming.",
     "https://github.com/Libr-AI/do-not-answer"),
    ("jailbreakv-28k", "JailBreakV-28K",
     "datasets", "safety-evals",
     "Large-scale dataset of 28,000 jailbreak prompts for benchmarking LLM safety.",
     "https://github.com/harishsg993010/JailBreakV-28K"),
    ("leaked-system-prompts", "Leaked System Prompts",
     "datasets", "safety-evals",
     "Collection of leaked system prompts from commercial AI tools — useful for understanding real-world prompt engineering and attack surfaces.",
     "https://github.com/harishsg993010/leaked-system-prompts"),
]

SKILL_TEMPLATE = """\
# {display_name}

**Category:** {category} / {subcategory}  
**Source:** [awesome-ai-security](https://github.com/ottosulin/awesome-ai-security) by [@ottosulin](https://github.com/ottosulin) · MIT License  
**Reference:** {ref_url}

## Description

{description}

## When to invoke

Invoke this skill when:
- Working on AI/LLM security assessments in the `{category}` domain
- Looking for tooling or guidance related to `{subcategory}`
- Among-Check agents need to understand the AI-security threat landscape

## Relevant Among-Check agents

{agents}

## Usage notes

- All tool execution must happen inside the Docker sandbox (`docs/sandbox.md`)
- Reference only when invoked from an editor session
- Check reference URL for latest version and documentation

## Safety rules

- Non-destructive probes only on authorized targets
- Never exfiltrate scan results to third parties
- Redact secrets and PII in evidence blocks
"""

AGENT_MAP = {
    "attack-red-teaming": "Red (`agent-vuln`), Commander (`orchestrator`)",
    "defense-controls": "Blue (`agent-config`), Green (`agent-infra`), Commander (`orchestrator`)",
    "governance-risk": "Commander (`orchestrator`), Blue (`agent-config`)",
    "learning-resources": "Commander (`orchestrator`)",
    "benchmarks-evals": "Commander (`orchestrator`), Red (`agent-vuln`)",
    "agentic-skills": "Commander (`orchestrator`), Pink (`agent-fix`)",
    "security-ai-models": "Commander (`orchestrator`), Red (`agent-vuln`)",
    "datasets": "Commander (`orchestrator`), Red (`agent-vuln`)",
}


def to_kebab(s: str) -> str:
    s = s.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    created = 0
    for (slug, display, category, subcategory, description, ref_url) in ENTRIES:
        skill_dir = os.path.join(OUT_DIR, slug)
        os.makedirs(skill_dir, exist_ok=True)
        skill_path = os.path.join(skill_dir, "SKILL.md")
        if os.path.exists(skill_path):
            continue
        agents = AGENT_MAP.get(category, "Commander (`orchestrator`)")
        content = SKILL_TEMPLATE.format(
            display_name=display,
            category=category,
            subcategory=subcategory,
            description=description,
            ref_url=ref_url,
            agents=agents,
        )
        with open(skill_path, "w") as f:
            f.write(content)
        created += 1

    # Write category README
    readme_path = os.path.join(OUT_DIR, "README.md")
    by_cat: dict[str, list] = {}
    for (slug, display, category, subcategory, desc, ref) in ENTRIES:
        by_cat.setdefault(category, []).append((slug, display, subcategory, desc))

    lines = [
        "# 30 — AI Security (awesome-ai-security)",
        "",
        "**Credit:** [awesome-ai-security](https://github.com/ottosulin/awesome-ai-security) "
        "by [@ottosulin](https://github.com/ottosulin) · MIT License",
        "",
        f"**{len(ENTRIES)} skills** covering AI/ML security tools, frameworks, standards, and attack techniques.",
        "",
        "---",
        "",
    ]
    for cat, items in sorted(by_cat.items()):
        lines.append(f"## {cat.replace('-', ' ').title()}")
        lines.append("")
        lines.append("| Skill | Subcategory | Description |")
        lines.append("|-------|-------------|-------------|")
        for slug, display, subcat, desc in sorted(items, key=lambda x: x[1].lower()):
            short_desc = desc[:80] + "…" if len(desc) > 80 else desc
            lines.append(f"| [{display}]({slug}/SKILL.md) | {subcat} | {short_desc} |")
        lines.append("")

    with open(readme_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Created {created} SKILL.md files in {OUT_DIR}")
    print(f"Categories: {list(by_cat.keys())}")
    print(f"Total: {len(ENTRIES)} entries")


if __name__ == "__main__":
    main()
